### ISSUE TITLE
ImportError: cannot import name 'PrepareModuleOutput' from 'torch.distributed.tensor.parallel' 

### ISSUE THREAD

**Issue by fahdmirza** [Vchitect/Vchitect-2.0#6]
Hello,

 Can I please request you to improve the README file ?

1) For example, what are the values of these?

test_file=$1
save_dir=$2
ckpt_path=$3

2) How exactly should we download these checkpoints from huggingface as there are multiple ways of doing it?

3) I am getting this error while running your inference.py script:

python3 inference.py --test_file "${test_file}" --save_dir "${save_dir}" --ckpt_path "${ckpt_path}"

Traceback (most recent call last):
  File "/home/Ubuntu/Vchitect-2.0/inference.py", line 2, in <module>
    from models.pipeline import VchitectXLPipeline
  File "/home/Ubuntu/Vchitect-2.0/models/pipeline.py", line 25, in <module>
    from models.VchitectXL import VchitectXLTransformerModel
  File "/home/Ubuntu/Vchitect-2.0/models/VchitectXL.py", line 34, in <module>
    from torch.distributed.tensor.parallel import (
ImportError: cannot import name 'PrepareModuleOutput' from 'torch.distributed.tensor.parallel' (/home/Ubuntu/miniconda3/envs/VchitectXL/lib/python3.11/site-packages/torch/distributed/tensor/parallel/__init__.py)

I would highly appreciate if I get some proper answer here as have already spent hours on it but in vain. Thanks.

**Comment by fahdmirza** [comment]
I was able to resolve above by upgrading torch and torchvision to latest version instead of versions given in read me.
